"""
This type stub file was generated by pyright.
"""

import sublime

"""
This type stub file was generated by pyright.
"""
class WindowCommand:
    window: sublime.Window
    ...


class EventListener:
    ...


