<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>MSSQL Query Results</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(\:\:)</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>--</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>Msg \d+, Level \d+, State \d+, Server (.*), Procedure \w+, Line \d+</string>
			<key>name</key>
			<string>sublimelinter.mark.error</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(\d rows affected\)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.mssql_query_results</string>
	<key>uuid</key>
	<string>417e7aab-61ba-4587-96d4-0572fed4bf75</string>
</dict>
</plist>
